name: auto-robotics-design
channels:
  - conda-forge
dependencies:
  - python = 3.10
  - numpy
  - scipy  
  - matplotlib 
  - pip
  - pip:
    - networkx
    - modern-robotics
    - notebook
    - mediapy
    - tqdm
    - trimesh
    - manifold3d
    - git+https://github.com/hauptmech/odio_urdf.git