name: j_moves_new
channels:
  - conda-forge
dependencies:
  - python = 3.10
  - numpy
  - scipy  
  - matplotlib 
  - pip
  - pinocchio 
  - pip:
    - networkx
    - pyparsing == 3.1.4
    - modern-robotics
    - notebook
    - mediapy
    - tqdm
    - trimesh==4.1.4
    - meshcat
    - numba
    - joblib
    - manifold3d
    - git+https://github.com/hauptmech/odio_urdf.git
    - pymoo
    - ipywidgets
